### ISSUE TITLE
Version of `app-starters-core-dependencies` is set to `${project.version}`

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-app-maven-plugin#11]
So this means that a new starter with version `1.0.0.BUILD-SNAPSHOT` will get generated with `1.0.0.BUILD-SNAPSHOT` as its `app-starters-core-dependencies` version.

**Comment by mbogoevici** [comment]
The current workaround is to add something like:

```
<additionalBoms>
						<bom>
							<name>app-starters-core-dependencies</name>
							<groupId>org.springframework.cloud.stream.app</groupId>
							<artifactId>app-starters-core-dependencies</artifactId>
							<version>1.1.2.BUILD-SNAPSHOT</version>
						</bom>
					</additionalBoms>
```

in the app generation section.

**Comment by sobychacko** [comment]
This is addressed through this commit in app-starters core: https://github.com/spring-cloud-stream-app-starters/core/commit/8def4d093ddc4bb91dc1b417889578730d00abc1

**Comment by mbogoevici** [comment]
LGTM - we can close this, I guess?

**Comment by sobychacko** [comment]
sure, I will close. Thnx!
